### ISSUE TITLE
Aboutus.html - layout/design - (Wednesday - Saturday AM/PM)

### ISSUE THREAD

**Issue by W-Tronvig** [W-Tronvig/Couch-Potatoes#34]
Aboutus.html - layout/design - (Wednesday - Saturday AM/PM)

Need three images (one of each of us)
Need three bios (5 sentences total - sort of a business pitch - similar to what would be on a LinkedIn profile - describing our current role as developers and our goals and current abilities, etc.)

**Comment by DavidChhing** [comment]
Finished with adding info. However I need images of each of us to add to the page. I also need to add some finishing touches with CSS.
